# Generated by Django 2.2.4 on 2020-12-17 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delve', '0004_auto_20201217_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='s3_file',
            name='ML_Result_fk',
        ),
        migrations.DeleteModel(
            name='ML_Result',
        ),
        migrations.DeleteModel(
            name='S3_File',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
