# Generated by Django 2.2.4 on 2020-12-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delve', '0007_ml_result_ml_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ml_result',
            name='date_run',
            field=models.DateTimeField(auto_now_add=True, default='null'),
            preserve_default=False,
        ),
    ]
