# Generated by Django 2.2.4 on 2020-12-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delve', '0010_ml_result_date_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ml_result',
            name='date_run',
            field=models.DateTimeField(),
        ),
    ]
