# Generated by Django 2.2.4 on 2020-12-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delve', '0011_auto_20201218_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ml_result',
            name='date_run',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
