# Generated by Django 2.2.4 on 2020-12-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delve', '0013_auto_20201218_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ml_result',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='s3_file',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
