# Generated by Django 2.2.4 on 2020-12-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delve', '0014_auto_20201218_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ml_result',
            name='by_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ml_result',
            name='ml_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
